asdf_plugins:
  - nodejs
  - golang
  - terraform
  - poetry
  - python
  - yarn
  - ansible-base

apt_packages:
  - unzip
  - build-essential
  - zlib1g-dev
  - make
  - libssl-dev
  - libbz2-dev 
  - libreadline-dev 
  - libsqlite3-dev
  - libffi-dev

dotfiles:
  - name: spacevim
    src: init.toml
    dest: "{{ lookup('env','HOME') }}/.SpaceVim.d/init.toml"
