bin_path: "{{ lookup('env','HOME') }}/.asdf/shims:{{ ansible_env.PATH }}"

asdf_plugins:
  # - ansible-base
  - nodejs
  - golang
  - terraform
  - poetry
  - python
  - yarn

apt_packages:
  - unzip
  - build-essential
  - zlib1g-dev
  - make
  - libssl-dev
  - libbz2-dev 
  - libreadline-dev 
  - libsqlite3-dev
  - libffi-dev
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

pip_packages:
  - pytest-testinfra

go_packages:
  - github.com/nektos/act@latest

dotfiles:
  - name: spacevim
    src: init.toml
    dest: "{{ lookup('env','HOME') }}/.SpaceVim.d/init.toml"
