bin_path: "{{ lookup('env','HOME') }}/.asdf/shims:{{ ansible_env.PATH }}"

asdf_plugins:
  # - ansible-base
  - nodejs
  - golang
  - terraform
  - poetry
  - python
  - yarn

apt_packages:
  - unzip
  - build-essential
  - zlib1g-dev
  - make
  - libssl-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libffi-dev
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - exa
  - ripgrep
  - bat

npm_packages:
  - how-2

pip_packages:
  - pytest-testinfra

go_packages:
  - github.com/nektos/act@latest

files_config:
  - name: spacevim
    src: init.toml
    dest: "{{ lookup('env','HOME') }}/.SpaceVim.d/init.toml"

bashrc_config:
  - "alias ls=exa" # use exa instead ls
  - "export EXA_COLORS='da=1;35'" # change color of date time for exa
  - "alias cat=bat" # use bat instead cat
  - "alias cat=batcat" # use bat instead cat (ubuntu & debian version)
