- name: Install packages
  shell: "npm list -g {{ item }} || npm install -g {{ item }}"
  with_items: "{{ npm_packages }}"
  environment:
    PATH: "{{ bin_path }}"

- name: Use commitizen with cz-conventional-changelog
  copy:
    content: '{ "path": "cz-conventional-changelog" }'
    dest: "${HOME}/.czrc"
